AdWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adtool.urls')),
    path('', include('users.urls')),
    path('password-reset/done', 
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ), 
        name='password_reset_done'
    ),
    path('password-reset-confirm/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ), 
        name='password_reset_confirm'
    ),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

]

"""
FOR PRODUCTION REMOVE ELSE AND CHANGE SETTINGS TO USE A FILE-SERVER
"""
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.png', upload_to='profile_pics')
    company = models.CharField(max_length=256, default="")
    location = models.CharField(max_length=256, default="")
    is_adclient = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        img = Image.open(self.image.path)
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'company', 'location']

users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required
# Create your views here.


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(
                request, f'{username} your account has been created! You can now login.')
            return redirect('users:login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', context={'form': form})


@login_required(login_url='users:login')
def profile(request):
    if request.method == 'POST':
        user_update_form = UserUpdateForm(request.POST, instance=request.user)
        profile_update_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile)
        if user_update_form.is_valid() and profile_update_form.is_valid():
            user_update_form.save()
            profile_update_form.save()
            messages.success(request, "Your account has been updated")
            return redirect('users:profile')
    else:
        user_update_form = UserUpdateForm(instance=request.user)
        profile_update_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'u_form': user_update_form,
        'p_form': profile_update_form
    }
    return render(request, 'users/profile.html', context)

users/templates/users/login.html
{% extends 'adtool/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<style>
    :root {
    --input-padding-x: .75rem;
    --input-padding-y: .75rem;
    }

    html,
    body {
        height: 100%;
    }

    body {
        display: -ms-flexbox;
        display: -webkit-box;
        display: flex;
        -ms-flex-align: center;
        -ms-flex-pack: center;
        -webkit-box-align: center;
        align-items: center;
        -webkit-box-pack: center;
        justify-content: center;
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
    }

    .form-signin {
        width: 100%;
        max-width: 420px;
        padding: 15px;
        margin: 0 auto;
    }

</style>
<div class="text-center">
    <form class="form-signin" method="POST" style="background-color: white;">
        <h1>AdWeb</h1>
        {% csrf_token %}
        <fieldset>
            <legend>Login</legend>
            {{ form|crispy }}
        </fieldset>
        <button type="submit" class="btn btn-primary btn-block">Login</button>
        <a href="{% url 'users:password_reset' %}"><small>Forgot password?</small></a>
        <p>Need an account? <a href="{% url 'users:register' %}">Register</a></p>
    </form>
</div>
{% endblock content %}

users/templates/users/logout.html
{% extends 'adtool/base.html' %}
{% block content %}
<div class="jumbotron text-center">
    <h1 class="display-4"><h2>You have been Logged Out</h2></h1>
    <hr class="my-4">
    <h5>Login Again? <a href="{% url 'users:login' %}">Login</a></h5>
</div>
{% endblock content %}

users/templates/users/password_reset.html
{% extends 'adtool/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<style>
    :root {
    --input-padding-x: .75rem;
    --input-padding-y: .75rem;
    }

    html,
    body {
        height: 100%;
    }

    body {
        display: -ms-flexbox;
        display: -webkit-box;
        display: flex;
        -ms-flex-align: center;
        -ms-flex-pack: center;
        -webkit-box-align: center;
        align-items: center;
        -webkit-box-pack: center;
        justify-content: center;
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #f5f5f5;
    }

    .form-signin {
        width: 100%;
        max-width: 420px;
        padding: 15px;
        margin: 0 auto;
    }

</style>
<div class="text-center">
    <form class="form-signin" method="POST" style="background-color: white;">
        <h1>AdWeb</h1>
        {% csrf_token %}
        <fieldset>
            <legend>Reset Password</legend>
            {{ form|crispy }}
        </fieldset>
        <button type="submit" class="btn btn-primary btn-block">Request Password Reset</button>
    </form>
</div>
{% endblock content %}

users/templates/users/password_reset_complete.html
{% extends 'adtool/base.html' %}
{% block content %}
<div class="alert alert-success">
    Password has been reset successfully
</div>
<a class="btn btn-success" href="{% url 'users:login' %}">Log In here</a>
{% endblock content %}

users/templates/users/password_reset_confirm.html
{% extends 'adtool/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}

<div class="text-center">
    <form class="form-signin" method="POST" style="background-color: white;">
        <h1>AdWeb</h1>
        {% csrf_token %}
        <fieldset>
            <legend>Reset Password</legend>
            {{ form|crispy }}
        </fieldset>
        <button type="submit" class="btn btn-info btn-block">Reset Password</button>
    </form>
</div>
{% endblock content %}

users/templates/users/password_reset_done.html
{% extends 'adtool/base.html' %}
{% block content %}
<div class="alert alert-info">
    An email has been sent with instructions to reset your password
</div>
{% endblock content %}

users/templates/users/profile.html
{% extends 'adtool/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="content-section">
    <div class="media">
        <div class="account-border">
            <img class="account-img account-border" src="{{ user.profile.image.url }}"
                style="display: block; border: 1px solid black ; border-radius: 10px;" id="image_tag">
        </div>
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
            <h6 class="h6">Want to change profile picture? Just add it here!</h3>
            <input
                form="profile-form"
                type="file"
                name="{{ p_form.image.name }}"
                id="{{ p_form.image.id_for_label }}"
                accept="image/*"
                {% if form.image.value != None %}
                    value="{{ p_form.image.value|stringformat:'s' }}"
                {% endif %}
            />
        </div>
    </div>
    <form id="profile-form" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Profile Info</legend>
            {{ u_form|crispy }}

            {% for field in p_form %}
                {% if field.id_for_label != 'id_image' %}
                    <div class="fieldWrapper">
                        {{ field.errors }}
                        {{ field|as_crispy_field }}
                        {% if field.help_text %}
                        <p class="help">{{ field.help_text|safe }}</p>
                        {% endif %}
                    </div>
                {% else %}
                {% endif %}
            {% endfor %}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Update</button>
        </div>
    </form>
</div>
{% endblock content %}

{% block javascript %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
<script type="text/javascript">
    const image_tag = '#image_tag'; // This is the id of img that'll change
    const id_image = '#{{ p_form.image.id_for_label }}'; // This is the id of the input tag that changes the image
    
    function readURL(input) {
        // Handling image input changing
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $(image_tag).attr('src', e.target.result);
                // isImageSet = true;
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $(id_image).change(function(){
        readURL(this);
    });
</script>
{% endblock javascript %}

users/templates/users/register.html
{% extends 'adtool/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="content-section">
    <form action="" method="post">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Join Today</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Register</button>
        </div>
        <div class="border-top pt-3">Already have an Account? <a href="{% url 'users:login' %}">Login</a></div>
    </form>
</div>
{% endblock content %}