AdWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('adtool.urls')),
    path('', include('users.urls')),
    path('password-reset/done', 
        auth_views.PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ), 
        name='password_reset_done'
    ),
    path('password-reset-confirm/<uidb64>/<token>/', 
        auth_views.PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ), 
        name='password_reset_confirm'
    ),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),

]

"""
FOR PRODUCTION REMOVE ELSE AND CHANGE SETTINGS TO USE A FILE-SERVER
"""
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

adtool/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.landing, name='landing'),
    path('home', views.AdvertisementListView.as_view(), name='home'),
    path('advertisement/<int:pk>/',
         views.AdvertisementDetailView.as_view(), name='detail'),
    path('advertisement/upload/',
         views.AdvertisementCreateView.as_view(), name='upload'),
    path('advertisement/<int:pk>/update/',
         views.AdvertisementUpdateView.as_view(), name='update'),
    path('advertisement/<int:pk>/delete/',
         views.AdvertisementDeleteView.as_view(), name='delete'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('api/<str:size>/<str:user_key>', views.Api.as_view(), name='api'),
    path('api/', views.Api.as_view(), name='api_post'),
    path('api/advertisement/<int:pk>/<int:site_pk>/<str:unique_key>/', views.ad_redir, name='ad_redir'),
    path('about/',views.about,name = 'about'),
    path('adclient/', views.register_website, name='register_website'),
    # AJAX:
    path('home/advertisement-enable-toggle-ajax/', views.enable_toggle, name='enable_toggle'),
    path('adclient/change-userkey/', views.change_userkey, name='change-userkey'),
    path('adclient/delete-userkey/', views.delete_userkey, name='delete-userkey'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', views.profile, name='profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
]

adtool/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone
from PIL import Image
import hashlib
import string
import secrets
from .custom_mixin import ModelDiffMixin
from django.contrib import messages

class Advertisement(models.Model, ModelDiffMixin):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='images/')
    url_link = models.URLField(default="")
    clicks = models.IntegerField(default=0)
    category = models.IntegerField(
        choices=(
            (0, 'science'),
            (1, 'math'),
            (2, 'anime'),
            (3, 'computers'),
            (4, 'nature'),
            (5, 'news'),
            (6, 'music'),
            (7, 'politics'),
            (8, 'anthology'),
            (9, 'medical'),
            (10, 'sports'),
            (11, 'fashion'),
            (12, 'others')
        ),
        default="others"
    )
    size = models.CharField(
            max_length=16, choices=(
            ('medium rectangle', '300x250 pixels'),
            ('large rectangle', '336x280 pixels'),
            ('leaderboard', '728x90 pixels'),
            ('half page', '300x600 pixels'),
            ('free size', 'free size')
        ), 
        default='free size'
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    publish_date = models.DateTimeField('date published', default=timezone.now)
    is_enabled = models.BooleanField(default=True)
    identification_key = models.CharField(max_length=32, default='0')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        if self.identification_key == '0':
            key = ''.join(secrets.choice(string.ascii_uppercase + string.digits + string.ascii_lowercase) for i in range(32))
            self.identification_key = key
        super(Advertisement, self).save(*args, **kwargs)
        if self.get_field_diff('size'):
            img = Image.open(self.image.path)
            width, height = img.size
            left = 0
            top = 0
            if self.size == 'medium rectangle':
                right = 300
                bottom = 250
                
            elif self.size == 'large rectangle':
                right = 336
                bottom = 280
                
            elif self.size == 'leaderboard':
                right = 728
                bottom = 90
                
            elif self.size == 'half page':
                right = 300
                bottom = 600
                
            elif self.size == 'free size':
                pass

            img = img.crop((left, top, right, bottom))
            img.save(self.image.path, img.format)

class Website(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    url = models.URLField()
    userkey = models.CharField(max_length=32, default='0')

    def __str__(self):
        return str(self.url)

    def save(self, *args, **kwargs):
        notfound = True
        while notfound:
            key = ''.join(secrets.choice(string.ascii_uppercase + string.digits + string.ascii_lowercase) for i in range(32))
            if not Website.objects.filter(userkey=key).exists():
                notfound = False
                self.userkey = key
        super(Website, self).save(*args, **kwargs)


class AdvertisementLog(models.Model):
    """
    unique_key is only valid till we get a click, otherwise we set the value to '1'.
    """
    ad = models.ForeignKey(Advertisement, on_delete=models.CASCADE)
    site = models.ForeignKey(Website, on_delete=models.PROTECT)
    click_date = models.DateTimeField('date clicked', default=timezone.now)
    view_date = models.DateTimeField('date viewed', default=timezone.now)
    unique_key = models.CharField(max_length=32, default='0')
    is_clicked = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.is_clicked:
            self.click_date = timezone.now()
            self.unique_key = '1'
        notfound = True
        if not self.is_clicked:
            while notfound:
                key = ''.join(secrets.choice(string.ascii_uppercase + string.digits + string.ascii_lowercase) for i in range(32))
                if not AdvertisementLog.objects.filter(unique_key=key, is_clicked=False).exists():
                    notfound = False
                    self.unique_key = key
        super(AdvertisementLog, self).save(*args, **kwargs)

adtool/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseNotFound, JsonResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.contrib import messages

from rest_framework.views import APIView
from .models import Advertisement, AdvertisementLog, Website
from adtool.advertisement_api import AdvertisementAPI
import secrets
import string
import json



class AdvertisementListView(LoginRequiredMixin, ListView):
    model = Advertisement
    template_name = 'adtool/home.html'
    context_object_name = 'Advertisements'
    paginate_by = 5

    def get_queryset(self):
        return Advertisement.objects.filter(user=self.request.user).order_by('-id')


class AdvertisementDetailView(LoginRequiredMixin, UserPassesTestMixin,  DetailView):
    model = Advertisement

    def test_func(self):
        advertisement = self.get_object()
        if self.request.user == advertisement.user:
            return True
        return False

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        log = serializers.serialize('json', self.get_object().advertisementlog_set.all(), fields=('pk', 'click_date', 'view_date', 'is_clicked'))
        context['click_log'] = log
        return context


class AdvertisementCreateView(LoginRequiredMixin, CreateView):
    model = Advertisement
    fields = ['name', 'size', 'image', 'url_link', 'category']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class AdvertisementUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Advertisement
    fields = ['name', 'image', 'url_link', 'size', 'category', 'is_enabled']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def test_func(self):
        advertisement = self.get_object()
        if self.request.user == advertisement.user:
            return True
        return False


class AdvertisementDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):

    model = Advertisement
    success_url = '/'

    def test_func(self):
        advertisement = self.get_object()
        if self.request.user == advertisement.user:
            return True
        return False


class Api(APIView):
    def get(self, request, size, user_key):
        try:
            advertisementapi = AdvertisementAPI(request, Advertisement, size)
            advertisement_html = advertisementapi.get_advertisement(user_key)
            return JsonResponse(advertisement_html, safe=False)
        except Exception as e:
            return JsonResponse("The Advertisement could not be displayed", safe=False)
    
    def post(self, request):
        try:
            size = request.POST['size']
            user_key = request.POST['key']
            advertisementapi = AdvertisementAPI(request, Advertisement, size)
            advertisement_html = advertisementapi.get_advertisement(user_key)
            return JsonResponse(advertisement_html, safe=False)
        except Exception as e:
            return JsonResponse("The Advertisement could not be displayed", safe=False)


def ad_redir(self, pk, site_pk, unique_key):
    try:
        w = Website.objects.get(pk=site_pk)
        ad = Advertisement.objects.get(pk=pk)
        ad.clicks += 1
        ad.save()
        a = AdvertisementLog.objects.get(unique_key=unique_key)
        a.is_clicked = True
        a.save()
        return redirect(str(Advertisement.objects.get(pk=pk).url_link))
    except Exception as e:
        return HttpResponseNotFound('Not Found')


@login_required
def dashboard(request):
    ads = Advertisement.objects.filter(user=request.user)
    alog_click_count = []
    alog_view_count = []
    for ad in ads:
        alog_view_count.append(ad.advertisementlog_set.all().count())
        alog_click_count.append(ad.advertisementlog_set.filter(is_clicked=True).count())
    ads = serializers.serialize('json', ads, fields=('name', 'clicks'))
    alog_click_count = json.dumps(alog_click_count)
    alog_view_count

    context = {
        'ads': ads,
        'alog_click_count': alog_click_count,
        'alog_view_count': alog_view_count,
    }
    return render(request, 'adtool/dashboard.html', context)

def landing(request):
    return render(request, 'adtool/landing.html')

def about(request):
    return render(request, 'adtool/about.html')

@login_required
def register_website(request):
    user = request.user
    if user.profile.is_adclient:
        if request.method == 'GET':
            w = Website.objects.filter(user=user)
            return render(request, 'adtool/website_key.html', context={'websites': w})
        elif request.method == 'POST':
                if request.POST['btn'] == 'add':
                    Website.objects.create(user=user, url=request.POST['website-url']).save()
                elif request.POST['btn'] == 'delete':
                    try:
                        Website.objects.get(user=user, url=request.POST['website-url']).delete()
                    except Exception as e:
                        pass

                return redirect('register_website')
    else:
        if request.method == 'POST':
            u_p = user.profile
            u_p.is_adclient = True
            u_p.save()
            Website.objects.create(user=user, url=request.POST['website-url']).save()
            messages.success(request, "Your account has been updated, now you can display ads on your website")
            return redirect('register_website')

        elif request.method == 'GET':
            return render(request, 'adtool/adclient_confirmation.html')


"""
AJAX SECTION
"""

def enable_toggle(request):

    if request.method == 'GET':
        try:
            ad_id = request.GET['ad_id']
            ad_key = request.GET['ad_key']
            toggleThisAd = Advertisement.objects.get(pk=ad_id, identification_key=ad_key)
            toggleThisAd.is_enabled = not toggleThisAd.is_enabled
            toggleThisAd.save()
            return HttpResponse("Success!") # Sending an success response
        except Exception as e:
            print(e)
            return HttpResponse("Failure!")
    else:
        return HttpResponse("Request method is not a GET")

def change_userkey(request):
    if request.method == 'GET':
        user_key = request.GET['key']
        try:
            w = Website.objects.get(userkey=user_key)
            w.save()
            userkey = w.userkey
            return HttpResponse(userkey)
        except Exception as e:
            return HttpResponse(status=404)

def delete_userkey(request):
    if request.method == 'GET':
        user_key = request.GET['key']
        try:
            w = Website.objects.get(userkey=user_key)
            w.delete()
            return HttpResponse(status=200)
        except Exception as e:
            return HttpResponse(status=404)

adtool/templates/adtool/about.html
{% extends 'adtool/base.html' %}
{% load static %}
{% block content %}
<div class="jumbotron">
    <h1 class="display-4">What is this site exactly about?</h1>
    <p class="lead">This service sends advertisements in HTML format to the backend of our service websites who want to display ads. It tracks the ads. Digital Advertisement Management.</p>
</div>
<div>
    <h1 class="display-4">Who are the makers?</h1>
    <div class="row">
        <div class="col-lg-4">
            <img src="{% static 'adtool/img/Shoumik.png' %}" class="rounded-circle" height="200" width="200">
            <h2 class="h2">Shoumik Gandre</h2>
        </div>
        <div class="col-lg-4">
            <img src="{% static 'adtool/img/Rushank.jpg' %}" class="rounded-circle" height="200" width="200">
            <h2 class="h2">Rushank Shah</h2>
        </div>
        <div class="col-lg-4">
            <img src="{% static 'adtool/img/Kimaya.jpg' %}" class="rounded-circle" height="200" width="200">
            <h2 class="h2">Kimaya Kelbaikar</h2>
        </div>
    </div>
</div>
{% endblock content %}

adtool/templates/adtool/adclient_confirmation.html
{% extends 'adtool/base.html' %}

{% block content %}
    <div class="jumbotron">
        <h1 class="display-4">Want to display Advertisements on your site?</h1>
        <p class="lead"></p>
        <hr class="my-4">
        <p>Click the button down below and proceed to add your websites</p>
        
        <form method="post" class="form" name="action" value="adclient-form">
            {% csrf_token %}
            <div class="form-group">
                <label for="exampleInputEmail1">Website Url</label>
                <input id="websiteurl" type="url" class="form-control mx-sm-3 mb-2" placeholder="enter website url" name="website-url" pattern="https://.*" required/>
            </div>
            <button type="submit" class="btn btn-primary">Yes, activate</button>
        </form>
    </div>
{% endblock content %}

adtool/templates/adtool/advertisement_confirm_delete.html
{% extends 'adtool/base.html' %}
{% block content %}
<div class="container">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h2 class="h2">Are you sure you want to delete this post?</h2>
        <h4 class="h4">{{ object.name }}</h4>
        <br>
        <img src="{{ object.ad_image.url }}" class="img-responsive" style="width: 50%; float: left; margin-right: 10px;">
        <p style="clear: left;"></p>
        <br>
        <div>
            <button type="submit" class="btn btn-outline-danger" >Yes, Delete</button>
            <a href="{% url 'detail' object.id %}" class="btn btn-outline-primary">Cancel</a>
        </div>
    </form>
</div>


{% endblock content %}

adtool/templates/adtool/advertisement_detail.html
{% extends 'adtool/base.html' %}
{% load static %}

{% block stylesheet %}
<style>
  .chartdiv {
    overflow-y: scroll;
    height: 520px;
  }
</style>
{% endblock stylesheet %}

{% block content %}
{% if object %}

<div>
    <div class="container">
        <legend>
            <h3 class="h3">
                {{ object.name }}
            </h3>
            <p class="card-text" id="ad-status-{{ advertisement.pk }}">status: {% if advertisement.is_enabled %} Enabled {% else %} Disabled {% endif %}</p>
            <button 
                class="btn btn-sm {% if advertisement.is_enabled %} btn-success {% else %} btn-secondary {% endif %}"
                name="{{ advertisement.identification_key }}" 
                id="ad-id-{{ advertisement.pk }}" 
                value="{{ advertisement.is_enabled }}"
                onclick="toggleEnabler('{{ advertisement.identification_key }}', 'ad-id-{{ advertisement.pk }}', this.value)"
            >
                {% if advertisement.is_enabled %} Click to disable {% else %} Click to enable {% endif %}
                
            </button>
            <a class="btn btn-outline-secondary btn-sm mt-1 mb-1" href="{% url 'update' advertisement.id %}">update</a>
            <a class="btn btn-outline-danger btn-sm mt-1 mb-1" href="{% url 'delete' advertisement.id %}">delete</a>
        </legend>
        <div>
            <img src="{{ object.image.url }}" class="img-responsive"
                style="float: left; margin-right: 10px;" />
        </div>
        <br>
        <p class="h6" style="clear:left;">Url: {{ object.url_link }}</p>
        <div class="card border-dark text-white lg-12">
            <div class="card-header bg-dark text-center">Clicks v/s Hours</div>
            <div class="card-body">
                <div class="chartdiv">
                    <canvas id="detail-click-chart" height="300px" class="card-text"></canvas>
                </div>
            </div>
        </div>

    </div>
  
</div>

{% endif %}
{% endblock content %}

{% block javascript %}
<script>
    click_log = JSON.parse("{{ click_log|escapejs }}")
</script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<script src="{% static 'adtool/js/detail_click_chart.js' %}"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="{% static 'adtool/js/home/enableToggle.js' %}"></script>
{% endblock javascript%}

adtool/templates/adtool/advertisement_form.html
{% extends 'adtool/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="row">
    <div class="col-lg-5">
        <!-- form -->
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-outline-dark">Upload</button>    
        </form>
    </div>
    <div class="col-lg-7">
        <!-- image -->
        {% if form.instance.image %}
        <img src="{{ form.instance.image.url }}" alt="advertisement image" id="profile-img-tag" />
        {% else %}
        <img src="{% static 'adtool/img/default_ad.png' %}" alt="advertisement image" id="profile-img-tag">
        {% endif %}
    </div>
</div>
{% endblock content %}

{% block javascript %}
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
<script type="text/javascript">

    const image_tag = '#profile-img-tag';
    const id_image = '#id_image';
    let isImageSet = false;
    switch($(image_tag).attr('src')) {
        case "{% static 'adtool/img/Medium Rectangle (300x250px).png' %}":
        case "{% static 'adtool/img/Large Rectangle (336x280px).png' %}":
        case "{% static 'adtool/img/Leaderboard (720x90px).png' %}":
        case "{% static 'adtool/img/Half Page (300x600px).png' %}":
        case "{% static 'adtool/img/default_ad.png' %}": isImageSet = false; break;
        default: isImageSet = true; break;
    }

    function readURL(input) {
        // Handling image input changing
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            
            reader.onload = function (e) {
                $(image_tag).attr('src', e.target.result);
                isImageSet = true;
            }
            reader.readAsDataURL(input.files[0]);
        }
    }
    $(id_image).change(function(){
        readURL(this);
    });

    function changeDefaultAd(select) {
        if (!isImageSet) {
            switch (select.value){
                case 'medium rectangle':
                    $(image_tag).attr('src', "{% static 'adtool/img/Medium Rectangle (300x250px).png' %}");
                    break;
                case 'large rectangle':
                    $(image_tag).attr('src', "{% static 'adtool/img/Large Rectangle (336x280px).png' %}");
                    break;
                case 'leaderboard':
                    $(image_tag).attr('src', "{% static 'adtool/img/Leaderboard (720x90px).png' %}");
                    break;
                case 'half page':
                    $(image_tag).attr('src', "{% static 'adtool/img/Half Page (300x600px).png' %}");
                    break;
                case 'free size':
                    $(image_tag).attr('src', "{% static 'adtool/img/default_ad.png' %}");
                    break;
            }
        }
        else {
            $(image_tag).css({'object-fit': 'none', 'object-position': 'left top'})
            switch (select.value){
                case 'medium rectangle':
                    $(image_tag).css({'width': 300, 'height': 250});
                    break;
                case 'large rectangle':
                    $(image_tag).css({'width': 336, 'height': 280});
                    break;
                case 'leaderboard':
                    $(image_tag).css({'width': 720, 'height': 90});
                    break;
                case 'half page':
                    $(image_tag).css({'width': 300, 'height': 600});
                    break;
                case 'free size':
                    $(image_tag).css({'object-fit': '', 'object-position': ''})
                    $(image_tag).css({'width': '', 'height': ''});
                    break;
                default: 
                    $(image_tag).css({'object-fit': '', 'object-position': ''})
                    $(image_tag).css({'width': '', 'height': ''});
                    break;
            }
        }
    }
    $('#id_size').change(function () {
        changeDefaultAd(this);
    });
</script>
{% endblock javascript%}

adtool/templates/adtool/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>AdWeb - {{ title }}</title>
    {% else %}
    <title>AdWeb</title>
    {% endif %}
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'adtool/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'adtool/css/sidebar.css' %}">
    {% block stylesheet %}{% endblock stylesheet %}
</head>

<body>

    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand mr-4" href="{% url 'landing' %}">AdWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarToggle">
                    <div class="navbar-nav mr-auto">
                        <a class="nav-item nav-link" href="{% url 'home' %}">Home</a>
                        <a class="nav-item nav-link" href="{% url 'register_website' %}">Adclient</a>
                        {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'dashboard' %}">Dashboard</a>
                        {% endif %}
                        <a class="nav-item nav-link" href="{% url 'about' %}">About</a>
                    </div>
                    <!-- Navbar Right Side -->
                    <div class="navbar-nav">
                        {% if user.is_authenticated %}
                        <a class="nav-item nav-link" href="{% url 'users:profile' %}">Profile</a>
                        <a class="nav-item nav-link" href="{% url 'upload' %}">New Ad</a>
                        <a class="nav-item nav-link" href="{% url 'users:logout' %}">Logout</a>
                        {% else %}
                        <a class="nav-item nav-link" href="{% url 'users:login' %}">Login</a>
                        <a class="nav-item nav-link" href="{% url 'users:register' %}">Register</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <!--
        <div id="sidebar">
            <ul>
                <li>Element A</li>
                <li>Element B</li>
                <li>Element C</li>
            </ul>
        </div>
    -->
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-12">
                {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
                {% endfor %}
                {% endif %}
                {% block content %}{% endblock content %}
            </div>
        </div>
    </main>
    <div id="particles-js"></div>
    

    <!-- Optional JavaScript -->
    <script src="{% static 'adtool/js/particles.js' %}"></script>
    <script src="{% static 'adtool/js/app.js' %}"> </script>
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!--script src="https://code.jquery.com/jquery-3.2.1.min.js"></script-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    {% block javascript %}{% endblock javascript %}
</body>

</html>

adtool/templates/adtool/dashboard.html
<!-- MAKE A GRAPH HERE, I'VE JUST MADE A TEST PIECHART... WE NEED A LINE/BAR graph for y = clicks, x = day -->
{% extends 'adtool/base.html' %}
{% load static %}

{% block stylesheet %}
<style>
  .chartdiv {
    overflow-y: scroll;
    height: 520px;
  }
</style>
{% endblock stylesheet %}

{% block content %}
<h2 class="text-center">Dashboard</h2>


<div class="card border-dark text-white lg-12">
    <div class="card-header bg-dark text-center">Advertisement v/s Clicks</div>
    <div class="card-body">
      <div class="chartdiv">
      <canvas id="myChart" height="320px"></canvas>
    </div>
    </div>
</div>

{% endblock content %}

{% block javascript %}
<script type="text/javascript">
  // This stores the django template variables of this page
  var ads = "{{ ads|escapejs }}";
  var alog_click_count = "{{ alog_click_count|escapejs }}";
  var alog_view_count = "{{ alog_view_count|escapejs }}";
  alog_click_count = JSON.parse(alog_click_count)
  alog_view_count = JSON.parse(alog_view_count)
  ads = JSON.parse(ads);
</script>

<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>
<!--script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.3/Chart.min.js"></script-->
<script src="{% static 'adtool/js/clicks_chart.js' %}"></script>
{% endblock javascript %}

adtool/templates/adtool/upload.html
<!-- This HTML PAGE IS REDUNDANT: USE 'advertisement_form.html' INSTEAD -->
{% extends 'adtool/base.html' %}

{% block content %}
{% load crispy_forms_tags %}
<div class="content-section">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Upload</button>
    </form>
</div>
{% endblock content %}